# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_ReaderTimer(object):
    def setupUi(self, ReaderTimer):
        if not ReaderTimer.objectName():
            ReaderTimer.setObjectName(u"ReaderTimer")
        ReaderTimer.resize(519, 400)
        ReaderTimer.setStyleSheet(u"background-color:rgb(244,244,244)")
        self.tabWidget = QTabWidget(ReaderTimer)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 520, 400))
        self.tabWidget.setMinimumSize(QSize(520, 400))
        self.tabWidget.setMaximumSize(QSize(1000000, 1000000))
        self.tabWidget.setTabBarAutoHide(True)
        self.tab0 = QWidget()
        self.tab0.setObjectName(u"tab0")
        self.ButtDel = QPushButton(self.tab0)
        self.ButtDel.setObjectName(u"ButtDel")
        self.ButtDel.setGeometry(QRect(200, 103, 40, 22))
        self.ButtStart = QPushButton(self.tab0)
        self.ButtStart.setObjectName(u"ButtStart")
        self.ButtStart.setGeometry(QRect(260, 40, 200, 95))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ButtStart.setFont(font)
        self.ButtStart.setStyleSheet(u"background-color:rgb(52,101,164);\n"
"color:rgb(255,255,255);")
        self.ButtPause = QPushButton(self.tab0)
        self.ButtPause.setObjectName(u"ButtPause")
        self.ButtPause.setGeometry(QRect(260, 240, 200, 95))
        self.ButtPause.setFont(font)
        self.ButtPause.setAutoFillBackground(False)
        self.ButtPause.setStyleSheet(u"background-color:rgb(255,165,79);\n"
"color:rgb(0,0,0);")
        self.ButtPause.setAutoDefault(False)
        self.ButtAdd = QPushButton(self.tab0)
        self.ButtAdd.setObjectName(u"ButtAdd")
        self.ButtAdd.setGeometry(QRect(200, 80, 40, 22))
        self.EditCountdown = QLineEdit(self.tab0)
        self.EditCountdown.setObjectName(u"EditCountdown")
        self.EditCountdown.setGeometry(QRect(40, 180, 200, 45))
        self.EditCountdown.setStyleSheet(u"background-color:rgb(255,255,255)")
        self.label_2 = QLabel(self.tab0)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 130, 200, 45))
        font1 = QFont()
        font1.setPointSize(10)
        self.label_2.setFont(font1)
        self.label = QLabel(self.tab0)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 30, 200, 45))
        self.label.setFont(font1)
        self.EditTimer = QLineEdit(self.tab0)
        self.EditTimer.setObjectName(u"EditTimer")
        self.EditTimer.setGeometry(QRect(40, 80, 160, 45))
        self.EditTimer.setStyleSheet(u"background-color:rgb(255,255,255)")
        self.ButtStop = QPushButton(self.tab0)
        self.ButtStop.setObjectName(u"ButtStop")
        self.ButtStop.setGeometry(QRect(260, 140, 200, 95))
        self.ButtStop.setFont(font)
        self.ButtStop.setStyleSheet(u"background-color:rgb(139,37,19);\n"
"color:rgb(255,255,255);")
        self.label_3 = QLabel(self.tab0)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 230, 200, 45))
        self.label_3.setFont(font1)
        self.CboxMode = QComboBox(self.tab0)
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.addItem("")
        self.CboxMode.setObjectName(u"CboxMode")
        self.CboxMode.setGeometry(QRect(40, 280, 200, 45))
        self.CboxMode.setStyleSheet(u"background-color:rgb(255,255,255)")
        self.tabWidget.addTab(self.tab0, "")
        self.tab_setting = QWidget()
        self.tab_setting.setObjectName(u"tab_setting")
        self.label_4 = QLabel(self.tab_setting)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 40, 100, 30))
        self.label_4.setFont(font1)
        self.CboxCycleMode = QComboBox(self.tab_setting)
        self.CboxCycleMode.addItem("")
        self.CboxCycleMode.addItem("")
        self.CboxCycleMode.addItem("")
        self.CboxCycleMode.setObjectName(u"CboxCycleMode")
        self.CboxCycleMode.setGeometry(QRect(150, 40, 161, 30))
        self.CboxCycleMode.setStyleSheet(u"background-color:rgb(245,245,245);\n"
"color:rgb(0,0,0);")
        self.EditCycleTimes = QLineEdit(self.tab_setting)
        self.EditCycleTimes.setObjectName(u"EditCycleTimes")
        self.EditCycleTimes.setGeometry(QRect(150, 80, 100, 30))
        self.EditCycleTimes.setStyleSheet(u"background-color:rgb(255,255,255)")
        self.ButtAddCt = QPushButton(self.tab_setting)
        self.ButtAddCt.setObjectName(u"ButtAddCt")
        self.ButtAddCt.setGeometry(QRect(250, 80, 30, 30))
        self.ButtDelCt = QPushButton(self.tab_setting)
        self.ButtDelCt.setObjectName(u"ButtDelCt")
        self.ButtDelCt.setGeometry(QRect(280, 80, 30, 30))
        self.label_6 = QLabel(self.tab_setting)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 80, 100, 30))
        self.label_6.setFont(font1)
        self.tabWidget.addTab(self.tab_setting, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 20, 200, 30))
        self.label_5.setFont(font1)
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 100, 400, 30))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 140, 200, 30))
        self.label_8.setFont(font1)
        self.LabelQR = QLabel(self.tab)
        self.LabelQR.setObjectName(u"LabelQR")
        self.LabelQR.setGeometry(QRect(140, 140, 200, 200))
        self.LabelQR.setPixmap(QPixmap(u"C:/Users/lichengxin/Pictures/\u8d5e\u52a9.jpeg"))
        self.LabelAddress = QLabel(self.tab)
        self.LabelAddress.setObjectName(u"LabelAddress")
        self.LabelAddress.setGeometry(QRect(40, 50, 400, 30))
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(ReaderTimer)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(ReaderTimer)
    # setupUi

    def retranslateUi(self, ReaderTimer):
        ReaderTimer.setWindowTitle("")
        self.ButtDel.setText(QCoreApplication.translate("ReaderTimer", u"-", None))
        self.ButtStart.setText(QCoreApplication.translate("ReaderTimer", u"\u5f00\u59cb", None))
        self.ButtPause.setText(QCoreApplication.translate("ReaderTimer", u"\u6682\u505c(lock)", None))
        self.ButtAdd.setText(QCoreApplication.translate("ReaderTimer", u"+", None))
        self.label_2.setText(QCoreApplication.translate("ReaderTimer", u"\u5012\u8ba1\u65f6\uff08S\uff09", None))
        self.label.setText(QCoreApplication.translate("ReaderTimer", u"\u5468\u671f\u95f4\u9694\uff08S\uff09", None))
        self.EditTimer.setText(QCoreApplication.translate("ReaderTimer", u"15", None))
        self.ButtStop.setText(QCoreApplication.translate("ReaderTimer", u"\u505c\u6b62", None))
        self.label_3.setText(QCoreApplication.translate("ReaderTimer", u"\u6267\u884c\u52a8\u4f5c", None))
        self.CboxMode.setItemText(0, QCoreApplication.translate("ReaderTimer", u"\u5411\u540e\u7ffb\u9875", None))
        self.CboxMode.setItemText(1, QCoreApplication.translate("ReaderTimer", u"\u5411\u4e0b\u7ffb\u9875", None))
        self.CboxMode.setItemText(2, QCoreApplication.translate("ReaderTimer", u"\u5411\u524d\u7ffb\u9875", None))
        self.CboxMode.setItemText(3, QCoreApplication.translate("ReaderTimer", u"\u5411\u4e0a\u7ffb\u9875", None))
        self.CboxMode.setItemText(4, QCoreApplication.translate("ReaderTimer", u"Enter", None))
        self.CboxMode.setItemText(5, QCoreApplication.translate("ReaderTimer", u"Space", None))
        self.CboxMode.setItemText(6, QCoreApplication.translate("ReaderTimer", u"Tab", None))
        self.CboxMode.setItemText(7, QCoreApplication.translate("ReaderTimer", u"Win/Cmd", None))
        self.CboxMode.setItemText(8, QCoreApplication.translate("ReaderTimer", u"Shift", None))
        self.CboxMode.setItemText(9, QCoreApplication.translate("ReaderTimer", u"Ctrl", None))
        self.CboxMode.setItemText(10, QCoreApplication.translate("ReaderTimer", u"\u8fd4\u56de\u684c\u9762", None))
        self.CboxMode.setItemText(11, QCoreApplication.translate("ReaderTimer", u"\u81ea\u52a8\u4fdd\u5b58", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), QCoreApplication.translate("ReaderTimer", u"\u8ba1\u65f6\u5668", None))
        self.label_4.setText(QCoreApplication.translate("ReaderTimer", u"\u5012\u8ba1\u65f6\u91cd\u590d\u6b21\u6570", None))
        self.CboxCycleMode.setItemText(0, QCoreApplication.translate("ReaderTimer", u"\u65e0\u9650\u5faa\u73af", None))
        self.CboxCycleMode.setItemText(1, QCoreApplication.translate("ReaderTimer", u"\u4ec5\u8ba1\u65f6\u4e00\u6b21", None))
        self.CboxCycleMode.setItemText(2, QCoreApplication.translate("ReaderTimer", u"\u81ea\u5b9a\u4e49", None))

        self.EditCycleTimes.setText(QCoreApplication.translate("ReaderTimer", u"0", None))
        self.ButtAddCt.setText(QCoreApplication.translate("ReaderTimer", u"+", None))
        self.ButtDelCt.setText(QCoreApplication.translate("ReaderTimer", u"-", None))
        self.label_6.setText(QCoreApplication.translate("ReaderTimer", u"\u81ea\u5b9a\u4e49\u6b21\u6570", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting), QCoreApplication.translate("ReaderTimer", u"\u8bbe\u7f6e", None))
        self.label_5.setText(QCoreApplication.translate("ReaderTimer", u"\u6700\u65b0\u7248\u672c\u4e0b\u8f7d\u5730\u5740\uff1a", None))
        self.label_7.setText(QCoreApplication.translate("ReaderTimer", u"\u5f00\u53d1\u4ea4\u6d41\u53ca\u95ee\u9898\u53cd\u9988QQ\u7fa4\uff1a790010416\uff0c\u5bc6\u7801\uff1agithub", None))
        self.label_8.setText(QCoreApplication.translate("ReaderTimer", u"\u652f\u6301\u4f5c\u8005\uff1a", None))
        self.LabelQR.setText("")
        self.LabelAddress.setText(QCoreApplication.translate("ReaderTimer", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("ReaderTimer", u"\u5176\u4ed6", None))
    # retranslateUi

